# coding: utf-8

"""
    RestCol API Documentations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_data_format import ApiDataFormat

class TestApiDataFormat(unittest.TestCase):
    """ApiDataFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiDataFormat(self):
        """Test ApiDataFormat"""
        # inst = ApiDataFormat()

if __name__ == '__main__':
    unittest.main()
