# coding: utf-8

"""
    RestCol API Documentations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rest_col_service_create_document_body import RestColServiceCreateDocumentBody

class TestRestColServiceCreateDocumentBody(unittest.TestCase):
    """RestColServiceCreateDocumentBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestColServiceCreateDocumentBody:
        """Test RestColServiceCreateDocumentBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestColServiceCreateDocumentBody`
        """
        model = RestColServiceCreateDocumentBody()
        if include_optional:
            return RestColServiceCreateDocumentBody(
                document_id = '',
                data = 'YQ==',
                dataformat = 'DATA_FORMAT_UNKNOWN'
            )
        else:
            return RestColServiceCreateDocumentBody(
        )
        """

    def testRestColServiceCreateDocumentBody(self):
        """Test RestColServiceCreateDocumentBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
