# coding: utf-8

"""
    RestCol API Documentations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.swagger_api import SwaggerApi


class TestSwaggerApi(unittest.TestCase):
    """SwaggerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SwaggerApi()

    def tearDown(self) -> None:
        pass

    def test_rest_col_service_get_swagger_doc(self) -> None:
        """Test case for rest_col_service_get_swagger_doc

        Return API Doc in Swagger
        """
        pass

    def test_rest_col_service_get_swagger_doc2(self) -> None:
        """Test case for rest_col_service_get_swagger_doc2

        Return API Doc in Swagger
        """
        pass


if __name__ == '__main__':
    unittest.main()
