# coding: utf-8

"""
    RestCol API Documentations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.collection_api import CollectionApi


class TestCollectionApi(unittest.TestCase):
    """CollectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionApi()

    def tearDown(self) -> None:
        pass

    def test_rest_col_service_create_collection(self) -> None:
        """Test case for rest_col_service_create_collection

        Add collection endpoint, a collection is a set of documents with scheme-free.
        """
        pass

    def test_rest_col_service_delete_collection(self) -> None:
        """Test case for rest_col_service_delete_collection

        """
        pass

    def test_rest_col_service_get_collection(self) -> None:
        """Test case for rest_col_service_get_collection

        """
        pass

    def test_rest_col_service_list_collections(self) -> None:
        """Test case for rest_col_service_list_collections

        list collections endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
