# coding: utf-8

"""
    RestCol API Documentations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.document_api import DocumentApi


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentApi()

    def tearDown(self) -> None:
        pass

    def test_rest_col_service_create_document(self) -> None:
        """Test case for rest_col_service_create_document

        """
        pass

    def test_rest_col_service_create_document2(self) -> None:
        """Test case for rest_col_service_create_document2

        """
        pass

    def test_rest_col_service_delete_document(self) -> None:
        """Test case for rest_col_service_delete_document

        DeleteDocument endpoint is a generic endpoint for deleting a specific data
        """
        pass

    def test_rest_col_service_get_document(self) -> None:
        """Test case for rest_col_service_get_document

        GetDocument endpoint is a generic endpoint for retrieving data across multiple collections
        """
        pass

    def test_rest_col_service_query_document(self) -> None:
        """Test case for rest_col_service_query_document

        """
        pass

    def test_rest_col_service_query_documents_stream(self) -> None:
        """Test case for rest_col_service_query_documents_stream

        """
        pass


if __name__ == '__main__':
    unittest.main()
