# coding: utf-8

"""
    RestCol API Documentations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ApiSchemaFieldDataType(str, Enum):
    """
    ApiSchemaFieldDataType
    """

    """
    allowed enum values
    """
    NONE = 'SCHEMA_FIELD_DATA_TYPE_NONE'
    SCHEMA_FIELD_DATA_TYPE_NONE = 'SCHEMA_FIELD_DATA_TYPE_NONE'
    SCHEMA_FIELD_DATA_TYPE_STRING = 'SCHEMA_FIELD_DATA_TYPE_STRING'
    SCHEMA_FIELD_DATA_TYPE_NUMBER = 'SCHEMA_FIELD_DATA_TYPE_NUMBER'
    SCHEMA_FIELD_DATA_TYPE_INTEGER = 'SCHEMA_FIELD_DATA_TYPE_INTEGER'
    SCHEMA_FIELD_DATA_TYPE_BOOL = 'SCHEMA_FIELD_DATA_TYPE_BOOL'
    SCHEMA_FIELD_DATA_TYPE_OBJECT = 'SCHEMA_FIELD_DATA_TYPE_OBJECT'
    SCHEMA_FIELD_DATA_TYPE_ARRAY = 'SCHEMA_FIELD_DATA_TYPE_ARRAY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApiSchemaFieldDataType from a JSON string"""
        return cls(json.loads(json_str))


