# coding: utf-8

"""
    RestCol API Documentations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ApiDataFormat(str, Enum):
    """
    ApiDataFormat
    """

    """
    allowed enum values
    """
    UNKNOWN = 'DATA_FORMAT_UNKNOWN'
    DATA_FORMAT_UNKNOWN = 'DATA_FORMAT_UNKNOWN'
    DATA_FORMAT_AUTO = 'DATA_FORMAT_AUTO'
    DATA_FORMAT_JSON = 'DATA_FORMAT_JSON'
    DATA_FORMAT_CSV = 'DATA_FORMAT_CSV'
    DATA_FORMAT_XML = 'DATA_FORMAT_XML'
    DATA_FORMAT_URL = 'DATA_FORMAT_URL'
    DATA_FORMAT_MEDIA = 'DATA_FORMAT_MEDIA'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApiDataFormat from a JSON string"""
        return cls(json.loads(json_str))


