# coding: utf-8

"""
    RestCol API Documentations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ApiCollectionType(str, Enum):
    """
    ApiCollectionType
    """

    """
    allowed enum values
    """
    COLLECTION_TYPE_NONE = 'COLLECTION_TYPE_NONE'
    COLLECTION_TYPE_REGULAR_FILES = 'COLLECTION_TYPE_REGULAR_FILES'
    COLLECTION_TYPE_TIMESERIES = 'COLLECTION_TYPE_TIMESERIES'
    COLLECTION_TYPE_TRANSACTION = 'COLLECTION_TYPE_TRANSACTION'
    COLLECTION_TYPE_VECTOR = 'COLLECTION_TYPE_VECTOR'
    COLLECTION_TYPE_PROXY = 'COLLECTION_TYPE_PROXY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApiCollectionType from a JSON string"""
        return cls(json.loads(json_str))


